{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "73de7df5-f92a-4c41-84c5-fbff9cbdf8bb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<>:67: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:105: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:67: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "<>:105: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "/var/folders/gw/vq2hsq313m32zf6hprs576nr0000gn/T/ipykernel_71352/1139840252.py:67: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  if bullet_state is 'ready':\n",
      "/var/folders/gw/vq2hsq313m32zf6hprs576nr0000gn/T/ipykernel_71352/1139840252.py:105: SyntaxWarning: \"is\" with a literal. Did you mean \"==\"?\n",
      "  if bullet_state is 'fire':\n"
     ]
    }
   ],
   "source": [
    "import pygame\n",
    "from pygame import mixer\n",
    "import random\n",
    "import math\n",
    "\n",
    "pygame.init()\n",
    "\n",
    "screen = pygame.display.set_mode((800,600))\n",
    "#screen.fill((150,150,150))\n",
    "pygame.display.set_caption('Invaders Game')\n",
    "\n",
    "\n",
    "#player\n",
    "playerimg=pygame.image.load('player.png')\n",
    "playerX,playerY=370,480\n",
    "playerX_change=0\n",
    "\n",
    "# Enemy\n",
    "enemyimg = pygame.image.load('enemy.png')\n",
    "enemyX = random.randint(0, 736)\n",
    "enemyY = random.randint(50, 150)\n",
    "enemyX_change, enemyY_change = 10, 40\n",
    "\n",
    "# Bullet\n",
    "bulletimg = pygame.image.load('bullet.png')\n",
    "bulletX, bulletY = 0, 480\n",
    "bulletX_change, bulletY_change = 0, 3\n",
    "bullet_state = 'ready'\n",
    "\n",
    "# Score\n",
    "score_value = 0\n",
    "\n",
    "\n",
    "def player(X,Y):\n",
    "    screen.blit(playerimg, (X, Y))\n",
    "\n",
    "def enemy(X, Y):\n",
    "    screen.blit(enemyimg, (X, Y))\n",
    "\n",
    "def fire_bullet(X, Y):\n",
    "    global bullet_state\n",
    "    bullet_state = 'fire'\n",
    "    screen.blit(bulletimg, (X + 16, Y + 10))\n",
    "\n",
    "def isCollision(enemyX, enemyY, bulletX, bulletY):\n",
    "    distance = math.sqrt(math.pow(enemyX - bulletX, 2) + math.pow(enemyY - bulletY, 2))\n",
    "    if distance < 27:\n",
    "        return True\n",
    "    else:\n",
    "        return False    \n",
    "    \n",
    "running=True\n",
    "while running:\n",
    "    \n",
    "    screen.fill((0,0,0,))\n",
    "    \n",
    "    for event in pygame.event.get():\n",
    "        if event.type == pygame.QUIT:\n",
    "            running=False\n",
    "            \n",
    "        if event.type == pygame.KEYDOWN:\n",
    "            if event.key == pygame.K_LEFT:\n",
    "                playerX_change = -1.5\n",
    "            if event.key == pygame.K_RIGHT:\n",
    "                playerX_change = 1.5\n",
    "            if event.key == pygame.K_SPACE:\n",
    "                if bullet_state is 'ready':\n",
    "                    bulletX = playerX\n",
    "                    fire_bullet(bulletX, bulletY)\n",
    "                    \n",
    "        if event.type == pygame.KEYUP:\n",
    "            if event.key == pygame.K_LEFT or event.key == pygame.K_RIGHT:\n",
    "                playerX_change = 0            \n",
    "          \n",
    "    playerX += playerX_change\n",
    "    if playerX <= 0:\n",
    "        playerX = 0\n",
    "    elif playerX >= 736:\n",
    "        playerX = 736\n",
    "        \n",
    "    #enemy\n",
    "    if enemyY > 440:\n",
    "        break\n",
    "    enemyX += enemyX_change\n",
    "    if enemyX <= 0: #左端に来たら\n",
    "        enemyX_change = 10\n",
    "        enemyY += enemyY_change\n",
    "    elif enemyX >=736: #右端に来たら\n",
    "        enemyX_change = -10\n",
    "        enemyY += enemyY_change\n",
    "        \n",
    "    collision = isCollision(enemyX, enemyY, bulletX, bulletY)\n",
    "    if collision:\n",
    "        bulletY = 480\n",
    "        bullet_state = 'ready'\n",
    "        score_value += 1\n",
    "        enemyX = random.randint(0, 736)\n",
    "        enemyY = random.randint(50, 150)\n",
    "\n",
    "    # Bullet Movement\n",
    "    if bulletY <=0:\n",
    "        bulletY = 480\n",
    "        bullet_state = 'ready'\n",
    "\n",
    "    if bullet_state is 'fire':\n",
    "        fire_bullet(bulletX, bulletY)\n",
    "        bulletY -= bulletY_change  \n",
    "\n",
    "        \n",
    "    # Score\n",
    "    font = pygame.font.SysFont(None, 32) # フォントの作成　Noneはデフォルトのfreesansbold.ttf\n",
    "    score = font.render(f\"Score : {str(score_value)}\", True, (255,255,255)) # テキストを描画したSurfaceの作成\n",
    "    screen.blit(score, (20,50))\n",
    "        \n",
    "    \n",
    "    \n",
    "    player(playerX,playerY)\n",
    "    enemy(enemyX,enemyY)\n",
    "    \n",
    "    pygame.display.update()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b3164e6-d167-475c-8cc8-2bf786311143",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6c92a141-fd6c-47b5-8352-c3aa62fdbcb2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
